#!/bin/bash
# Copyright (c) 2014 Samsung Electronics Co., Ltd All Rights Reserved
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [ ! `which cpplint.py` ]; then
   echo -e "\nPlease make sure cpplint.py is in your PATH. It is part of depot_tools inside Chromium repository."
   exit 1
fi

OLDPWD=$PWD
BASE=`dirname $0`
cd $BASE/..

# filters
FILTERS="-readability/streams,-build/c++11"

cpplint.py --filter="$FILTERS" $(find . \( -name '*.hxx' -o -name '*.cxx' \) )
RET=$?

JS_RET_VAL=$?
cd $OLDPWD

if [ "x$RET" == "x0" ]; then
  exit 0
else
  exit 1
fi
